spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/udemy2-db'
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa.hibernate:
    ddl-auto: none

keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'UdemyManagement'
  resource: 'udemy-spring-client'
  public-client: true