spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/udemy2-db'
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa.hibernate:
    ddl-auto: none

keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'UdemyManagement'
  resource: 'udemy-spring-client'
  credentials:
    secret: 'c80fea20-23e9-4c74-96c4-6a9bc17f990e'