spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa.hibernate:
    ddl-auto: none

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_SECRET}